/*
 * This file was automatically generated by EvoSuite
 */

package org.jbehave.core.failures;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import org.jbehave.core.failures.FailingUponPendingStep;


public class FailingUponPendingStepEvoSuiteTest {


  //Test case number: 0
  /*
   * 2 covered goals:
   * 1 org.jbehave.core.failures.FailingUponPendingStep.handleFailure(Ljava/lang/Throwable;)V: root-Branch
   * 2 org.jbehave.core.failures.FailingUponPendingStep.<init>()V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      FailingUponPendingStep failingUponPendingStep0 = new FailingUponPendingStep();
      Throwable throwable0 = null;
      try {
        failingUponPendingStep0.handleFailure((Throwable) null);
      }catch(NullPointerException e) {
        /*
         * no message in exception (getMessage() returned null)
         */
        /*
      %%%<ex><className val="NullPointerException"/><stackDepth val="14"/><causeDepth val="0"/><source val="org.jbehave.core.failures.FailingUponPendingStep.handleFailure(FailingUponPendingStep.java:6)"/></ex>%%%
         */
      }
  }
}
